project:
  type: website
  output-dir: docs
  resources: "jspsych/"

website:
  title: "A Spatial Cognitive Interference Test?"
  navbar:
    right:
      - about.qmd
     
format:
  html:
    theme: journal
    css: styles.css

editor: visual

